language: python

python:
  - "3.6"

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.1

before_install:
  # install newer compose version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  # Workaround for https://github.com/travis-ci/travis-ci/issues/4842
  # Let's stop postgresql
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

install:
  - docker-compose up -d --build

script:
  - docker-compose up -d db caluma
  - docker-compose run --rm interval black --check .
  - docker-compose run --rm interval flake8
  - docker-compose run --rm interval wait-for-it.sh db:5432
  - docker-compose run --rm interval wait-for-it.sh caluma:8000
  - docker-compose run --rm interval pytest --no-cov-on-fail --cov
